import { router } from "expo-router";
import React, { useState } from "react";

import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  Alert,
  ActivityIndicator,
  useWindowDimensions,
} from "react-native";

import {
  CameraView,
  useCameraPermissions,
} from "expo-camera";

export default function MemberScannerScreen() {
  // ============================================================
  // SCREEN SIZE
  // ============================================================

  const { width, height } = useWindowDimensions();

  // ============================================================
  // CAMERA PERMISSION
  // ============================================================

  const [permission, requestPermission] =
    useCameraPermissions();

  // ============================================================
  // STATES
  // ============================================================

  const [scanned, setScanned] = useState(false);

  const [cameraReady, setCameraReady] =
    useState(false);

  // ============================================================
  // SCANNER SIZE
  // ============================================================

  const FRAME_SIZE = Math.min(
    280,
    width - 70
  );

  // ============================================================
  // SCANNER POSITION
  // ============================================================

  const FRAME_TOP = Math.max(
    310,
    (height - FRAME_SIZE) / 2
  );

  const FRAME_LEFT =
    (width - FRAME_SIZE) / 2;

  // ============================================================
  // CAMERA ERROR
  // ============================================================

  const handleCameraError = (error) => {
    console.log(
      "================================"
    );

    console.log(
      "GYMRYT CAMERA ERROR"
    );

    console.log(error);

    console.log(
      "================================"
    );

    Alert.alert(
      "Camera Error",
      error?.message ||
        "The camera could not be started."
    );
  };

  // ============================================================
  // CAMERA READY
  // ============================================================

  const handleCameraReady = () => {
    console.log(
      "GYMRYT CAMERA READY"
    );

    setCameraReady(true);
  };

  // ============================================================
  // DETECT QR TYPE
  // ============================================================

  const detectQRType = (data) => {
    if (!data) {
      return null;
    }

    // ----------------------------------------------------------
    // MEMBER QR
    //
    // Existing GymRyt member registration QR
    // Example:
    // GYMRYT_....
    // ----------------------------------------------------------

    if (data.startsWith("GYMRYT_")) {
      return "MEMBER";
    }

    // ----------------------------------------------------------
    // TRAINER QR
    //
    // Your trainer registration QR is a signed token.
    //
    // The token currently generated by Django contains:
    //
    // {"type":"TRAINER", ...}
    //
    // The token therefore starts with a JWT/Base64-style
    // encoded payload.
    // ----------------------------------------------------------

    try {
      const parts = data.split(":");

      if (parts.length >= 3) {
        const encodedPayload = parts[0];

        // Convert URL-safe Base64 to normal Base64
        const base64 = encodedPayload
          .replace(/-/g, "+")
          .replace(/_/g, "/");

        const padded =
          base64 +
          "=".repeat(
            (4 - (base64.length % 4)) % 4
          );

        const decoded = decodeURIComponent(
          atob(padded)
            .split("")
            .map(
              (char) =>
                "%" +
                ("00" +
                  char.charCodeAt(0).toString(16)
                ).slice(-2)
            )
            .join("")
        );

        const payload = JSON.parse(decoded);

        if (
          payload &&
          payload.type === "TRAINER"
        ) {
          return "TRAINER";
        }
      }
    } catch (error) {
      console.log(
        "Trainer QR payload detection failed:",
        error
      );
    }

    return null;
  };

  // ============================================================
  // QR CODE SCANNED
  // ============================================================

  const handleBarcodeScanned = ({ data }) => {
    // ----------------------------------------------------------
    // Prevent multiple scans
    // ----------------------------------------------------------

    if (scanned) {
      return;
    }

    console.log(
      "================================"
    );

    console.log(
      "GYMRYT QR CODE DETECTED:"
    );

    console.log(data);

    console.log(
      "================================"
    );

    // ==========================================================
    // DETECT QR TYPE
    // ==========================================================

    const qrType = detectQRType(data);

    console.log(
      "GYMRYT QR TYPE:",
      qrType
    );

    // ==========================================================
    // INVALID QR
    // ==========================================================

    if (!qrType) {
      Alert.alert(
        "Invalid QR Code",
        "This is not a valid GymRyt member or trainer registration QR code.",
        [
          {
            text: "SCAN AGAIN",
            onPress: () => {
              setScanned(false);
            },
          },
        ]
      );

      return;
    }

    // ==========================================================
    // VALID QR
    // ==========================================================

    setScanned(true);

    // ==========================================================
    // TRAINER QR
    // ==========================================================

    if (qrType === "TRAINER") {
      console.log(
        "GYMRYT TRAINER QR DETECTED"
      );

      console.log(
        "Opening trainer registration..."
      );

      router.push({
        pathname: "/trainer/registration",

        params: {
          qrToken: data,
        },
      });

      return;
    }

    // ==========================================================
    // MEMBER QR
    // ==========================================================

    if (qrType === "MEMBER") {
      console.log(
        "GYMRYT MEMBER QR DETECTED"
      );

      console.log(
        "Opening member registration..."
      );

      router.push({
        pathname: "/member/register",

        params: {
          qrToken: data,
        },
      });

      return;
    }
  };

  // ============================================================
  // PERMISSION LOADING
  // ============================================================

  if (!permission) {
    return (
      <View style={styles.loadingScreen}>
        <ActivityIndicator
          size="large"
          color="#2563EB"
        />

        <Text style={styles.loadingText}>
          Checking camera permission...
        </Text>
      </View>
    );
  }

  // ============================================================
  // PERMISSION NOT GRANTED
  // ============================================================

  if (!permission.granted) {
    return (
      <View style={styles.permissionScreen}>
        <View style={styles.permissionIcon}>
          <Text style={styles.permissionIconText}>
            📷
          </Text>
        </View>

        <Text style={styles.permissionTitle}>
          Camera Access Required
        </Text>

        <Text style={styles.permissionText}>
          GymRyt needs access to your camera to
          scan the gym registration QR code.
        </Text>

        <TouchableOpacity
          style={styles.allowButton}
          onPress={requestPermission}
          activeOpacity={0.8}
        >
          <Text style={styles.allowButtonText}>
            ALLOW CAMERA
          </Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.backButton}
          onPress={() => router.back()}
          activeOpacity={0.8}
        >
          <Text style={styles.backButtonText}>
            GO BACK
          </Text>
        </TouchableOpacity>
      </View>
    );
  }

  // ============================================================
  // MAIN SCREEN
  // ============================================================

  return (
    <View style={styles.container}>

      {/* ========================================================
          HEADER
          ======================================================== */}

      <View style={styles.header}>
        <Text style={styles.title}>
          SCAN GYM QR
        </Text>

        <Text style={styles.subtitle}>
          Scan the QR code provided by your gym
        </Text>
      </View>

      {/* ========================================================
          CAMERA BOX
          ======================================================== */}

      <View
        style={[
          styles.cameraBox,
          {
            width: FRAME_SIZE,
            height: FRAME_SIZE,
            top: FRAME_TOP,
            left: FRAME_LEFT,
          },
        ]}
      >
        <CameraView
          style={styles.camera}
          facing="back"
          mode="picture"
          onCameraReady={handleCameraReady}
          onMountError={handleCameraError}
          onBarcodeScanned={
            scanned
              ? undefined
              : handleBarcodeScanned
          }
          barcodeScannerSettings={{
            barcodeTypes: ["qr"],
          }}
        />

        {/* ======================================================
            CAMERA LOADING
            ====================================================== */}

        {!cameraReady && (
          <View
            style={styles.cameraLoading}
            pointerEvents="none"
          >
            <ActivityIndicator
              size="large"
              color="#FFFFFF"
            />

            <Text style={styles.cameraLoadingText}>
              Starting camera...
            </Text>
          </View>
        )}
      </View>

      {/* ========================================================
          SCANNER BORDER
          ======================================================== */}

      <View
        pointerEvents="none"
        style={[
          styles.scannerCorners,
          {
            width: FRAME_SIZE,
            height: FRAME_SIZE,
            top: FRAME_TOP,
            left: FRAME_LEFT,
          },
        ]}
      >
        <View
          style={[
            styles.corner,
            styles.topLeft,
          ]}
        />

        <View
          style={[
            styles.corner,
            styles.topRight,
          ]}
        />

        <View
          style={[
            styles.corner,
            styles.bottomLeft,
          ]}
        />

        <View
          style={[
            styles.corner,
            styles.bottomRight,
          ]}
        />
      </View>

      {/* ========================================================
          CLOSE BUTTON
          ======================================================== */}

      <TouchableOpacity
        style={styles.closeButton}
        onPress={() => router.back()}
        activeOpacity={0.8}
      >
        <Text style={styles.closeButtonText}>
          ×
        </Text>
      </TouchableOpacity>

      {/* ========================================================
          BOTTOM INSTRUCTIONS
          ======================================================== */}

      <View style={styles.bottomContent}>
        <Text style={styles.instruction}>
          Place the QR code inside the frame
        </Text>

        <Text style={styles.secureText}>
          🔒 Secure GymRyt registration
        </Text>
      </View>

      {/* ========================================================
          PROCESSING
          ======================================================== */}

      {scanned && (
        <View style={styles.processingOverlay}>
          <ActivityIndicator
            size="large"
            color="#FFFFFF"
          />

          <Text style={styles.processingText}>
            Opening registration...
          </Text>
        </View>
      )}

    </View>
  );
}

// ============================================================
// STYLES
// ============================================================

const styles = StyleSheet.create({

  container: {
    flex: 1,
    backgroundColor: "#000000",
    position: "relative",
    overflow: "hidden",
  },

  header: {
    position: "absolute",
    top: 90,
    left: 0,
    right: 0,
    alignItems: "center",
    paddingHorizontal: 20,
    zIndex: 20,
  },

  title: {
    color: "#FFFFFF",
    fontSize: 25,
    fontWeight: "800",
    letterSpacing: 1,
    textAlign: "center",
  },

  subtitle: {
    color: "#E2E8F0",
    fontSize: 12,
    marginTop: 8,
    textAlign: "center",
  },

  cameraBox: {
    position: "absolute",
    backgroundColor: "#000000",
    overflow: "hidden",
    borderRadius: 4,
    zIndex: 5,
  },

  camera: {
    width: "100%",
    height: "100%",
  },

  cameraLoading: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },

  cameraLoadingText: {
    color: "#FFFFFF",
    fontSize: 13,
    marginTop: 12,
  },

  scannerCorners: {
    position: "absolute",
    zIndex: 50,
    pointerEvents: "none",
  },

  corner: {
    position: "absolute",
    width: 48,
    height: 48,
    borderColor: "#FFFFFF",
    zIndex: 60,
  },

  topLeft: {
    top: 0,
    left: 0,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopLeftRadius: 12,
  },

  topRight: {
    top: 0,
    right: 0,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopRightRadius: 12,
  },

  bottomLeft: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomLeftRadius: 12,
  },

  bottomRight: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomRightRadius: 12,
  },

  closeButton: {
    position: "absolute",
    top: 45,
    left: 22,
    width: 45,
    height: 45,
    borderRadius: 23,
    backgroundColor: "rgba(0,0,0,0.75)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },

  closeButtonText: {
    color: "#FFFFFF",
    fontSize: 32,
    fontWeight: "300",
    lineHeight: 34,
  },

  bottomContent: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 70,
    alignItems: "center",
    paddingHorizontal: 20,
    zIndex: 20,
  },

  instruction: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },

  secureText: {
    color: "#CBD5E1",
    fontSize: 10,
    marginTop: 10,
    textAlign: "center",
  },

  processingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.85)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 200,
  },

  processingText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
    marginTop: 15,
  },

  permissionScreen: {
    flex: 1,
    backgroundColor: "#050816",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 30,
  },

  permissionIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#172554",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },

  permissionIconText: {
    fontSize: 36,
  },

  permissionTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 10,
  },

  permissionText: {
    color: "#94A3B8",
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
    marginBottom: 28,
  },

  allowButton: {
    width: "100%",
    height: 54,
    backgroundColor: "#2563EB",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    elevation: 6,
  },

  allowButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.7,
  },

  backButton: {
    width: "100%",
    height: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#334155",
    alignItems: "center",
    justifyContent: "center",
  },

  backButtonText: {
    color: "#94A3B8",
    fontSize: 12,
    fontWeight: "700",
  },

  loadingScreen: {
    flex: 1,
    backgroundColor: "#050816",
    alignItems: "center",
    justifyContent: "center",
  },

  loadingText: {
    color: "#FFFFFF",
    fontSize: 14,
    marginTop: 15,
  },

});