import { router } from "expo-router";
import React, { useState } from "react";

import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  Alert,
  ActivityIndicator,
  useWindowDimensions,
} from "react-native";

import {
  CameraView,
  useCameraPermissions,
} from "expo-camera";

import { Ionicons } from "@expo/vector-icons";

import { useTheme } from "../context/ThemeContext";

export default function MemberScannerScreen() {
  const { colors } = useTheme();

  // ============================================================
  // SCREEN SIZE
  // ============================================================

  const { width, height } = useWindowDimensions();

  // ============================================================
  // CAMERA PERMISSION
  // ============================================================

  const [permission, requestPermission] =
    useCameraPermissions();

  // ============================================================
  // STATES
  // ============================================================

  const [scanned, setScanned] = useState(false);

  const [cameraReady, setCameraReady] =
    useState(false);

  // ============================================================
  // SCANNER SIZE
  // ============================================================

  const FRAME_SIZE = Math.min(
    280,
    width - 70
  );

  // ============================================================
  // SCANNER POSITION
  // ============================================================

  const FRAME_TOP = Math.max(
    310,
    (height - FRAME_SIZE) / 2
  );

  const FRAME_LEFT =
    (width - FRAME_SIZE) / 2;

  // ============================================================
  // CAMERA ERROR
  // ============================================================

  const handleCameraError = (error) => {
    console.log(
      "================================"
    );

    console.log(
      "GYMRYT CAMERA ERROR"
    );

    console.log(error);

    console.log(
      "================================"
    );

    Alert.alert(
      "Camera Error",
      error?.message ||
        "The camera could not be started."
    );
  };

  // ============================================================
  // CAMERA READY
  // ============================================================

  const handleCameraReady = () => {
    console.log(
      "GYMRYT CAMERA READY"
    );

    setCameraReady(true);
  };

  // ============================================================
  // DETECT QR TYPE
  // ============================================================

  const detectQRType = (data) => {
    if (!data) {
      return null;
    }

    // Canonical trainer payload generated by Django.
    if (data.startsWith("GYMRYT:TRAINER:")) {
      return "TRAINER";
    }

    // Allows already-issued database-backed trainer QR images to be scanned
    // until owners regenerate them after this release.
    if (data.startsWith("GYMRYT_TRAINER_")) {
      return "TRAINER";
    }

    // Migration support for the former Django ``signing.dumps`` trainer QR.
    // This only determines navigation; Django verifies its signature before
    // accepting it and resolves it to a RegistrationQR record.
    try {
      const encodedPayload = data.split(":")[0];
      const base64 = encodedPayload
        .replace(/-/g, "+")
        .replace(/_/g, "/");
      const padded = base64 + "=".repeat((4 - (base64.length % 4)) % 4);
      const decoded = decodeURIComponent(
        atob(padded)
          .split("")
          .map((char) =>
            `%${(`00${char.charCodeAt(0).toString(16)}`).slice(-2)}`
          )
          .join("")
      );

      if (JSON.parse(decoded)?.type === "TRAINER") {
        return "TRAINER";
      }
    } catch (_error) {
      // Not a legacy signed trainer payload.
    }

    // Existing member-registration payload. Keep this flow unchanged.
    if (data.startsWith("GYMRYT_")) {
      return "MEMBER";
    }

    return null;
  };

  // ============================================================
  // QR CODE SCANNED
  // ============================================================

  const handleBarcodeScanned = ({ data }) => {
    // ----------------------------------------------------------
    // Prevent multiple scans
    // ----------------------------------------------------------

    if (scanned) {
      return;
    }

    console.log(
      "================================"
    );

    console.log(
      "GYMRYT QR CODE DETECTED:"
    );

    console.log(data);

    console.log(
      "================================"
    );

    // ==========================================================
    // DETECT QR TYPE
    // ==========================================================

    const qrType = detectQRType(data);

    console.log(
      "GYMRYT QR TYPE:",
      qrType
    );

    // ==========================================================
    // INVALID QR
    // ==========================================================

    if (!qrType) {
      Alert.alert(
        "Invalid QR Code",
        "This is not a valid GymRyt member or trainer registration QR code.",
        [
          {
            text: "SCAN AGAIN",
            onPress: () => {
              setScanned(false);
            },
          },
        ]
      );

      return;
    }

    // ==========================================================
    // VALID QR
    // ==========================================================

    setScanned(true);

    // ==========================================================
    // TRAINER QR
    // ==========================================================

    if (qrType === "TRAINER") {
      console.log(
        "GYMRYT TRAINER QR DETECTED"
      );

      console.log(
        "Opening trainer registration..."
      );

      router.push({
        pathname: "/trainer/registration",

        params: {
          qrToken: data,
        },
      });

      return;
    }

    // ==========================================================
    // MEMBER QR
    // ==========================================================

    if (qrType === "MEMBER") {
      console.log(
        "GYMRYT MEMBER QR DETECTED"
      );

      console.log(
        "Opening member registration..."
      );

      router.push({
        pathname: "/member/register",

        params: {
          qrToken: data,
        },
      });

      return;
    }
  };

  // ============================================================
  // PERMISSION LOADING
  // ============================================================

  if (!permission) {
    return (
      <View
        style={[
          styles.loadingScreen,
          { backgroundColor: colors.background },
        ]}
      >
        <ActivityIndicator
          size="large"
          color={colors.primary}
        />

        <Text
          style={[
            styles.loadingText,
            { color: colors.mutedText },
          ]}
        >
          Checking camera permission...
        </Text>
      </View>
    );
  }

  // ============================================================
  // PERMISSION NOT GRANTED
  // ============================================================

  if (!permission.granted) {
    return (
      <View
        style={[
          styles.permissionScreen,
          { backgroundColor: colors.background },
        ]}
      >
        <View
          style={[
            styles.permissionCard,
            {
              backgroundColor: colors.card,
              borderColor: colors.border,
            },
          ]}
        >
          <View
            style={[
              styles.permissionIcon,
              { backgroundColor: colors.iconBackground },
            ]}
          >
            <Ionicons
              name="camera-outline"
              size={30}
              color={colors.primaryLight}
            />
          </View>

          <Text
            style={[
              styles.permissionEyebrow,
              { color: colors.primaryLight },
            ]}
          >
            GYMRYT • QR SCANNER
          </Text>

          <Text
            style={[
              styles.permissionTitle,
              { color: colors.text },
            ]}
          >
            Camera Access Required
          </Text>

          <Text
            style={[
              styles.permissionText,
              { color: colors.secondaryText },
            ]}
          >
            GymRyt needs access to your camera to
            scan the gym registration QR code.
          </Text>

          <TouchableOpacity
            style={[
              styles.allowButton,
              { backgroundColor: colors.primary },
            ]}
            onPress={requestPermission}
            activeOpacity={0.8}
          >
            <Ionicons
              name="camera"
              size={18}
              color="#FFFFFF"
            />

            <Text style={styles.allowButtonText}>
              ALLOW CAMERA
            </Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={[
              styles.backButton,
              { borderColor: colors.border },
            ]}
            onPress={() => router.back()}
            activeOpacity={0.8}
          >
            <Text
              style={[
                styles.backButtonText,
                { color: colors.secondaryText },
              ]}
            >
              GO BACK
            </Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  // ============================================================
  // MAIN SCREEN
  // ============================================================

  return (
    <View style={styles.container}>

      {/* ========================================================
          HEADER
          ======================================================== */}

      <View style={styles.header}>
        <Text
          style={[
            styles.eyebrow,
            { color: colors.primaryLight },
          ]}
        >
          GYMRYT • REGISTRATION
        </Text>

        <Text style={styles.title}>
          Scan Gym QR
        </Text>

        <Text style={styles.subtitle}>
          Scan the QR code provided by your gym
        </Text>
      </View>

      {/* ========================================================
          CAMERA BOX
          ======================================================== */}

      <View
        style={[
          styles.cameraBox,
          {
            width: FRAME_SIZE,
            height: FRAME_SIZE,
            top: FRAME_TOP,
            left: FRAME_LEFT,
          },
        ]}
      >
        <CameraView
          style={styles.camera}
          facing="back"
          mode="picture"
          onCameraReady={handleCameraReady}
          onMountError={handleCameraError}
          onBarcodeScanned={
            scanned
              ? undefined
              : handleBarcodeScanned
          }
          barcodeScannerSettings={{
            barcodeTypes: ["qr"],
          }}
        />

        {/* ======================================================
            CAMERA LOADING
            ====================================================== */}

        {!cameraReady && (
          <View
            style={styles.cameraLoading}
            pointerEvents="none"
          >
            <ActivityIndicator
              size="large"
              color="#FFFFFF"
            />

            <Text style={styles.cameraLoadingText}>
              Starting camera...
            </Text>
          </View>
        )}
      </View>

      {/* ========================================================
          SCANNER BORDER
          ======================================================== */}

      <View
        pointerEvents="none"
        style={[
          styles.scannerCorners,
          {
            width: FRAME_SIZE,
            height: FRAME_SIZE,
            top: FRAME_TOP,
            left: FRAME_LEFT,
          },
        ]}
      >
        <View
          style={[
            styles.corner,
            styles.topLeft,
            { borderColor: colors.primaryLight },
          ]}
        />

        <View
          style={[
            styles.corner,
            styles.topRight,
            { borderColor: colors.primaryLight },
          ]}
        />

        <View
          style={[
            styles.corner,
            styles.bottomLeft,
            { borderColor: colors.primaryLight },
          ]}
        />

        <View
          style={[
            styles.corner,
            styles.bottomRight,
            { borderColor: colors.primaryLight },
          ]}
        />
      </View>

      {/* ========================================================
          CLOSE BUTTON
          ======================================================== */}

      <TouchableOpacity
        style={styles.closeButton}
        onPress={() => router.back()}
        activeOpacity={0.8}
      >
        <Ionicons
          name="arrow-back"
          size={20}
          color="#FFFFFF"
        />
      </TouchableOpacity>

      {/* ========================================================
          BOTTOM INSTRUCTIONS
          ======================================================== */}

      <View style={styles.bottomContent}>
        <View style={styles.instructionPill}>
          <Ionicons
            name="scan-outline"
            size={16}
            color={colors.primaryLight}
          />

          <Text style={styles.instruction}>
            Place the QR code inside the frame
          </Text>
        </View>

        <View style={styles.secureRow}>
          <Ionicons
            name="lock-closed"
            size={11}
            color="#CBD5E1"
          />

          <Text style={styles.secureText}>
            Secure GymRyt registration
          </Text>
        </View>
      </View>

      {/* ========================================================
          PROCESSING
          ======================================================== */}

      {scanned && (
        <View style={styles.processingOverlay}>
          <ActivityIndicator
            size="large"
            color="#FFFFFF"
          />

          <Text style={styles.processingText}>
            Opening registration...
          </Text>
        </View>
      )}
    </View>
  );
}

// ============================================================
// STYLES
// ============================================================

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000000",
    position: "relative",
    overflow: "hidden",
  },

  header: {
    position: "absolute",
    top: 90,
    left: 0,
    right: 0,
    alignItems: "center",
    paddingHorizontal: 20,
    zIndex: 20,
  },

  eyebrow: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.4,
  },

  title: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    marginTop: 4,
    textAlign: "center",
  },

  subtitle: {
    color: "#E2E8F0",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 6,
    textAlign: "center",
  },

  cameraBox: {
    position: "absolute",
    backgroundColor: "#000000",
    overflow: "hidden",
    borderRadius: 20,
    zIndex: 5,
  },

  camera: {
    width: "100%",
    height: "100%",
  },

  cameraLoading: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },

  cameraLoadingText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 12,
  },

  scannerCorners: {
    position: "absolute",
    zIndex: 50,
    pointerEvents: "none",
  },

  corner: {
    position: "absolute",
    width: 48,
    height: 48,
    zIndex: 60,
  },

  topLeft: {
    top: 0,
    left: 0,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopLeftRadius: 20,
  },

  topRight: {
    top: 0,
    right: 0,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopRightRadius: 20,
  },

  bottomLeft: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomLeftRadius: 20,
  },

  bottomRight: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomRightRadius: 20,
  },

  closeButton: {
    position: "absolute",
    top: 45,
    left: 18,
    width: 43,
    height: 43,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },

  bottomContent: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 70,
    alignItems: "center",
    paddingHorizontal: 20,
    zIndex: 20,
  },

  instructionPill: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    backgroundColor: "rgba(0,0,0,0.6)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },

  instruction: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    marginLeft: 7,
  },

  secureRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },

  secureText: {
    color: "#CBD5E1",
    fontSize: 9,
    fontWeight: "700",
    marginLeft: 4,
  },

  processingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.85)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 200,
  },

  processingText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    marginTop: 14,
  },

  permissionScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },

  permissionCard: {
    width: "100%",
    maxWidth: 420,
    borderWidth: 1,
    borderRadius: 26,
    paddingHorizontal: 18,
    paddingVertical: 24,
    alignItems: "center",
  },

  permissionIcon: {
    width: 64,
    height: 64,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },

  permissionEyebrow: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.4,
  },

  permissionTitle: {
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 4,
    marginBottom: 8,
  },

  permissionText: {
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 17,
    textAlign: "center",
    marginBottom: 22,
  },

  allowButton: {
    width: "100%",
    height: 54,
    borderRadius: 17,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 10,
  },

  allowButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1,
  },

  backButton: {
    width: "100%",
    height: 50,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },

  backButtonText: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
  },

  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },

  loadingText: {
    fontSize: 12,
    fontWeight: "700",
    marginTop: 12,
  },
});
