# Generated by Django 5.2.17 on 2026-09-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_registrationqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
    ]
