# Generated by Django 5.2.17 on 2026-09-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_membership_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationqr',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
