# Generated by Django 5.2.17 on 2026-09-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_trainer_userprofile_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='member_profiles/'),
        ),
    ]
