# Generated by Django 5.2.17 on 2026-09-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Gym Owner'), ('OWNER_TRAINER', 'Owner + Trainer'), ('TRAINER', 'Trainer'), ('MEMBER', 'Member')], default='OWNER', max_length=20),
        ),
    ]
