# Generated by Django 5.2.17 on 2026-09-07 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationqr',
            name='registration_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('TRAINER', 'Trainer')], default='MEMBER', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='registrationqr',
            constraint=models.UniqueConstraint(fields=('admin', 'workspace', 'registration_type'), name='unique_registration_qr_per_type'),
        ),
    ]
