# Generated by Django 5.2.17 on 2026-09-08 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_trainerapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerapplication',
            name='password',
        ),
        migrations.AddField(
            model_name='trainerapplication',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerapplication',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainerapplication',
            name='specialization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_profiles/'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__is_trainer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'status'], name='members_mem_workspa_90322c_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['trainer', 'status'], name='members_mem_trainer_25d0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['admin', 'status'], name='members_mem_admin_i_9bcc98_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationqr',
            index=models.Index(fields=['workspace', 'registration_type', 'is_active'], name='members_reg_workspa_f1ad53_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerapplication',
            index=models.Index(fields=['workspace', 'status'], name='members_tra_workspa_b6a236_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerapplication',
            index=models.Index(fields=['admin', 'status'], name='members_tra_admin_i_35b455_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['workspace', 'is_active'], name='members_tra_workspa_733c23_idx'),
        ),
    ]
