# Generated by Django 5.2.17 on 2026-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_remove_trainerapplication_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerapplication',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
