# Generated by Django 5.2.17 on 2026-09-16 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_workoutplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('TRAINER_APPLICATION', 'Trainer Application'), ('NEW_MEMBER', 'New Member'), ('TRAINER_ASSIGNED', 'Trainer Assigned'), ('WORKOUT_UPLOADED', 'Workout Uploaded'), ('MEMBERSHIP_EXPIRING', 'Membership Expiring'), ('MEMBERSHIP_EXPIRED', 'Membership Expired'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('MEMBER_REMOVED', 'Member Removed'), ('WELCOME', 'Welcome')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_id', models.BigIntegerField(blank=True, null=True)),
                ('related_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='members_not_recipie_d85515_idx'), models.Index(fields=['workspace', 'created_at'], name='members_not_workspa_78c8c7_idx'), models.Index(fields=['notification_type', 'created_at'], name='members_not_notific_6e4b66_idx')],
            },
        ),
    ]
