# Generated by Django 5.2.17 on 2026-09-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_notification_recipient_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('primary_muscle', models.CharField(max_length=100)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('gif_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['primary_muscle'], name='members_exe_primary_c6e33a_idx'), models.Index(fields=['equipment'], name='members_exe_equipme_ce2a32_idx'), models.Index(fields=['is_active'], name='members_exe_is_acti_d4fd65_idx')],
            },
        ),
    ]
